const Ipsum = () => {
    return (
      <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut justo eget velit porta bibendum. Etiam velit augue, sagittis ut hendrerit sed, blandit vel quam. Maecenas mollis ultrices dolor, id egestas augue iaculis id. Integer semper urna libero, ut congue elit congue ut. Morbi a elementum orci. Sed consectetur ipsum at fermentum feugiat. Fusce dignissim mi vitae dui venenatis pharetra. Nulla sodales diam sem, et ullamcorper magna tincidunt quis.

Morbi vestibulum molestie dolor, vitae sodales nulla tincidunt et. Fusce mi nulla, egestas at suscipit ac, condimentum in nisl. Ut a sapien et mauris faucibus auctor. Sed quis mi ante. Nunc in ultricies ipsum. Sed in mi ut orci rutrum ultricies. Cras tellus erat, dignissim sed odio sit amet, dapibus tempus arcu. Cras dignissim nisi tempor rhoncus lacinia. Aenean sem erat, ullamcorper in bibendum eu, volutpat congue enim. Morbi molestie vehicula luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Maecenas eget nisi ut sem aliquet feugiat. Maecenas id dolor purus. Pellentesque feugiat maximus diam, sit amet maximus massa maximus vel. Mauris vulputate cursus auctor. Donec eget nulla sed nulla dictum ullamcorper eu vel orci. Suspendisse dictum vestibulum faucibus. Suspendisse nec tortor felis. Cras tortor urna, volutpat et ante vel, fringilla interdum magna. Phasellus et ligula ex. Morbi volutpat sapien molestie metus vehicula pulvinar. Curabitur felis massa, porta at varius sit amet, sodales sed lectus. Nullam eget nunc ullamcorper, auctor purus non, bibendum mauris. Praesent vitae elementum magna. Nullam elementum, ipsum quis tristique consequat, nulla metus convallis erat, in pharetra ipsum erat vel velit. Phasellus iaculis tincidunt mauris.

Nulla semper efficitur purus ac aliquam. Quisque eu congue libero. Nulla venenatis commodo enim, et accumsan tellus congue in. Vivamus non ligula et mauris commodo sodales at sed diam. Nam est odio, varius non dictum sit amet, luctus nec eros. Suspendisse dictum tellus felis, eget vulputate justo blandit sit amet. Fusce a ipsum non risus gravida sollicitudin. Vivamus id nisl non sapien blandit iaculis vitae tempus lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam felis elit, viverra gravida ipsum imperdiet, facilisis porta massa. Proin maximus porta leo nec auctor. Donec aliquam ultrices mauris, sed hendrerit libero accumsan et. Cras imperdiet odio id est maximus congue.

Mauris dictum euismod consectetur. Praesent fringilla ligula felis, quis convallis risus efficitur at. Aliquam a faucibus urna. Quisque pulvinar suscipit turpis in ullamcorper. Etiam interdum lacinia sapien. Proin sit amet hendrerit magna. Etiam molestie eros ac orci interdum accumsan. Curabitur molestie risus neque, a condimentum nisl mattis vitae. Morbi vitae imperdiet nulla, ut imperdiet neque. Nulla vel massa ac urna viverra ultrices sed id odio. Ut lacinia libero a pharetra euismod. Proin gravida ex quis libero porta condimentum. Vestibulum est nisl, ullamcorper a tellus ut, tempor varius enim. Cras id neque maximus, pulvinar dui sed, malesuada justo. Nulla lacus ante, malesuada id mauris eu, dapibus venenatis massa. Nunc hendrerit mi in nisl congue, nec aliquam purus hendrerit.</p>
      </div>
    )
  }
  
  export default Ipsum